import { useState, type ReactElement } from "react"
import katex from "katex"
import "katex/dist/katex.min.css"

interface MathBlockProps {
  value: string
  displayMode: boolean
}

export function MathBlock({ value, displayMode }: MathBlockProps): ReactElement {
  const [showSource, setShowSource] = useState(false)

  let renderedHtml: string | null = null
  let renderError: string | null = null

  try {
    renderedHtml = katex.renderToString(value, {
      displayMode,
      throwOnError: true,
      strict: false,
    })
  } catch (err) {
    renderError = err instanceof Error ? err.message : "Math could not be rendered"
  }

  if (!displayMode) {
    if (renderedHtml) {
      // Safe: renderedHtml is generated by KaTeX from LaTeX input, not raw user HTML
      return <span dangerouslySetInnerHTML={{ __html: renderedHtml }} />
    }
    return <code>{value}</code>
  }

  return (
    <div className="chat-math-block">
      <div className="chat-math-block__header">
        <span className="chat-math-block__label">math</span>
        <button
          className="chat-math-block__toggle"
          onClick={() => setShowSource(!showSource)}
          type="button"
        >
          {showSource ? "View rendered" : "View source"}
        </button>
      </div>
      <div className="chat-math-block__body">
        {renderError && (
          <div className="chat-math-block__error">{renderError}</div>
        )}
        {showSource || renderError ? (
          <pre className="chat-math-block__source">
            <code>{value}</code>
          </pre>
        ) : renderedHtml ? (
          // Safe: renderedHtml is generated by KaTeX from LaTeX input, not raw user HTML
          <div
            className="chat-math-block__rendered"
            dangerouslySetInnerHTML={{ __html: renderedHtml }}
          />
        ) : null}
      </div>
    </div>
  )
}
