import { useState, useEffect, useRef, type ReactElement } from "react"
import mermaid from "mermaid"

interface MermaidBlockProps {
  value: string
}

let mermaidInitialized = false

function initMermaid() {
  if (mermaidInitialized) return
  mermaid.initialize({
    startOnLoad: false,
    theme: "dark",
    themeVariables: {
      primaryColor: "rgba(91,141,239,0.15)",
      primaryBorderColor: "#5b8def",
      primaryTextColor: "#eef1f8",
      secondaryColor: "rgba(199,146,234,0.12)",
      secondaryBorderColor: "#c792ea",
      tertiaryColor: "rgba(195,232,141,0.12)",
      tertiaryBorderColor: "#c3e88d",
      lineColor: "#5b8def",
      textColor: "#eef1f8",
      mainBkg: "rgba(91,141,239,0.15)",
      nodeBorder: "#5b8def",
      clusterBkg: "rgba(255,255,255,0.03)",
      titleColor: "#eef1f8",
      edgeLabelBackground: "#1a1d27",
    },
  })
  mermaidInitialized = true
}

export function MermaidBlock({ value }: MermaidBlockProps): ReactElement {
  const [svgHtml, setSvgHtml] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [showSource, setShowSource] = useState(false)
  const containerRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    let cancelled = false
    initMermaid()

    const id = "mermaid-" + Date.now() + "-" + Math.random().toString(36).slice(2)
    mermaid
      .render(id, value)
      .then(({ svg }) => {
        if (!cancelled) setSvgHtml(svg)
      })
      .catch((err) => {
        if (!cancelled) setError(err instanceof Error ? err.message : "Diagram could not be rendered")
      })

    return () => {
      cancelled = true
    }
  }, [value])

  return (
    <div className="chat-mermaid-block">
      <div className="chat-mermaid-block__header">
        <span className="chat-mermaid-block__label">mermaid</span>
        <button
          className="chat-mermaid-block__toggle"
          onClick={() => setShowSource(!showSource)}
          type="button"
        >
          {showSource ? "View diagram" : "View source"}
        </button>
      </div>
      <div className="chat-mermaid-block__body">
        {error && (
          <div className="chat-mermaid-block__error">{error}</div>
        )}
        {showSource || error ? (
          <pre className="chat-mermaid-block__source">
            <code>{value}</code>
          </pre>
        ) : svgHtml ? (
          <div
            ref={containerRef}
            className="chat-mermaid-block__diagram"
            // The SVG content here is generated by the mermaid library from diagram source,
            // not from raw user HTML input, so XSS risk is minimal.
            dangerouslySetInnerHTML={{ __html: svgHtml }}
          />
        ) : (
          <pre className="chat-mermaid-block__source">
            <code>{value}</code>
          </pre>
        )}
      </div>
    </div>
  )
}
