#!/usr/bin/env tsx
/**
 * Reads skill markdown files from vendor/superpowers/skills/ and generates
 * a TypeScript module exporting bundled skill strings for system prompt injection.
 *
 * Run: pnpm run bundle-skills
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs"
import { join, dirname, basename } from "node:path"

const ROOT = join(import.meta.dirname, "..")
const SKILLS_DIR = join(ROOT, "vendor/superpowers/skills")
const OUT_FILE = join(ROOT, "packages/shared/src/generated/bundled-skills.ts")

// Planning skills — injected in main chat sessions
const PLANNING_SKILLS = [
  "brainstorming",
  "writing-plans",
]

// Execution skills — injected in thread/coordinator sessions (alongside planning)
const EXECUTION_SKILLS = [
  "using-git-worktrees",
  "executing-plans",
  "subagent-driven-development",
  "test-driven-development",
  "verification-before-completion",
  "finishing-a-development-branch",
]

// Shared/core skills — injected in both session types
const SHARED_SKILLS = [
  "systematic-debugging",
  "requesting-code-review",
  "receiving-code-review",
  "dispatching-parallel-agents",
]

// Excluded:
// - writing-skills: meta skill about authoring skills, 40KB+ (too large, irrelevant at runtime)
// - using-superpowers: meta skill about Claude Code's skill discovery (Ultra handles injection)

/**
 * Read all .md files in a skill directory and concatenate them.
 * SKILL.md comes first, then any supplementary files.
 */
function readSkillFull(name: string): string {
  const skillDir = join(SKILLS_DIR, name)
  const files = readdirSync(skillDir)
    .filter((f) => f.endsWith(".md"))
    .sort((a, b) => {
      // SKILL.md first, then alphabetical
      if (a === "SKILL.md") return -1
      if (b === "SKILL.md") return 1
      return a.localeCompare(b)
    })

  const parts: string[] = []
  for (const file of files) {
    const filePath = join(skillDir, file)
    if (!statSync(filePath).isFile()) continue
    const content = readFileSync(filePath, "utf-8").trim()
    if (file === "SKILL.md") {
      parts.push(content)
    } else {
      parts.push(`### ${basename(file, ".md")}\n\n${content}`)
    }
  }

  return parts.join("\n\n")
}

function bundleSkills(names: string[]): string {
  return names
    .map((name) => `<!-- skill: ${name} -->\n${readSkillFull(name)}`)
    .join("\n\n---\n\n")
}

const PREAMBLE = `<ultra-skills>
IMPORTANT: The workflow skills below are pre-loaded into this session.
Do NOT use the Skill tool to invoke superpowers skills — use these instructions directly.
All other skills and plugins (context7, Linear, etc.) may be used normally via the Skill tool.
`

const EPILOGUE = `\n</ultra-skills>`

const planning = bundleSkills(PLANNING_SKILLS)
const execution = bundleSkills(EXECUTION_SKILLS)
const shared = bundleSkills(SHARED_SKILLS)

const planningBundle = `${PREAMBLE}\n## Planning Skills\n\n${planning}\n\n## Shared Skills\n\n${shared}${EPILOGUE}`
const allBundle = `${PREAMBLE}\n## Planning Skills\n\n${planning}\n\n## Execution Skills\n\n${execution}\n\n## Shared Skills\n\n${shared}${EPILOGUE}`

const output = `// AUTO-GENERATED by scripts/bundle-skills.ts — do not edit
// Re-run: pnpm run bundle-skills

export const PLANNING_SKILLS = ${JSON.stringify(planningBundle)}

export const EXECUTION_SKILLS = ${JSON.stringify(execution)}

export const ALL_SKILLS = ${JSON.stringify(allBundle)}

export type SkillSessionType = "chat" | "thread"

export function getSkillBundle(sessionType: SkillSessionType): string {
  return sessionType === "thread" ? ALL_SKILLS : PLANNING_SKILLS
}
`

writeFileSync(OUT_FILE, output, "utf-8")
console.log(`Wrote ${OUT_FILE} (planning: ${(planningBundle.length / 1024).toFixed(1)}KB, all: ${(allBundle.length / 1024).toFixed(1)}KB)`)
